# Generated by Django 2.2.6 on 2019-10-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Item is ready to be purchased'), ('Sold', 'Item is already purchased'), ('Sold Out', 'Item is comming soon')], default='Sold', max_length=40)),
                ('issues', models.CharField(default='No Issues', max_length=40)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('mobile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Mobile')),
            ],
            bases=('product.mobile',),
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('mobile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Mobile')),
            ],
            bases=('product.mobile',),
        ),
        migrations.CreateModel(
            name='Xiaomi',
            fields=[
                ('mobile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Mobile')),
            ],
            bases=('product.mobile',),
        ),
    ]
